# Generated by Django 4.2.20 on 2025-04-08 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0002_teacher_salary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='profile_pic',
            field=models.ImageField(default='image/teacher/default.png', upload_to='profile_pic/Teacher/'),
        ),
    ]
