# Generated by Django 4.2.20 on 2025-04-13 08:05

import django.core.validators
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_alter_teacher_profile_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='joined_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='teacher',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='salary',
            field=models.PositiveIntegerField(default=0, help_text='Monthly salary in local currency', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
