# Generated by Django 4.2.20 on 2025-04-13 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_teacher_joined_date_teacher_updated_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacher',
            name='salary',
        ),
        migrations.AddField(
            model_name='teacher',
            name='subject',
            field=models.CharField(default='General', help_text='Main subject taught by this teacher', max_length=100),
        ),
    ]
