# Generated by Django 4.2.20 on 2025-04-14 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_alter_student_id'),
        ('teacher', '0005_remove_teacher_salary_teacher_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='blocked_students',
            field=models.ManyToManyField(blank=True, help_text='Students blocked by this teacher', related_name='blocked_by_teachers', to='student.student'),
        ),
    ]
